name: CI/CD Pipeline 09-06-2025

on:
  push:
    branches:
      - main

jobs:
  test_jobs:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: step 2
        run: echo "Segunda step"
          
      - name: step 3
        run: echo "Terceira step"

      - name: step 4
        run: echo "Quarto step"