name: CI/CD Pipeline 09-06-2025

on:
  push:
    branches:
      - main

jobs:
  test_jobs:
    runs-on: ubuntu-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          # Username used to log against the Docker registry
          username: 'williamdoxv'
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

          
