name: Teste Workflow

on:
  push:
    branches: [ main, developer ]

jobs:
  test_jobs:
    name: Executando o job de Teste
    runs-on: ubuntu-hosted

    steps:
      - name: Step 1
        uses: actions/checkout@v4
      
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: 'williamdoxv'
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

          
